---
output:
  html_document:
    theme: flatly
params:
  year:
    label: "Year"
    value: 2016
    input: numeric
    min: 2015
    max: 2017
    step: 1
  months:
    label: "Months"
    value: !r month.name
    input: select
    choices: !r month.name
    multiple: TRUE
---

### Check-ins and cancelations for `r params$year` {.tabset}

<br/>

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(ggplot2)
library(ggtext)
library(plotly)

source("core_functions.R")
```

```{r}
hotels_orig <- read.csv("tidy_tues_hotels.csv")
```

```{r}
hotels_data <- 
  hotels_orig %>% 
  mutate(arrival_ymd = lubridate::ymd(arrival_ymd)) %>%
  filter(arrival_year == params$year)
```

```{r}
gen_monthly_plot <- function(month) {
  process_df(month) %>% 
    gen_plot() %>% 
    make_interactive()
}

gen_monthly_section <- function(month) {
  if (nrow(process_df(month)) == 0) {
    return(invisible())
  }
  
  cat(paste("\n#### ", month))
  cat("\n\n<br/>\n\n")
  
  # return every plot, not just the last one generated in the final (iteration) function call
  gen_monthly_plot(month) %>% 
    print()
  
  # for something more complicated, you might want to use knitr::knit_expand with glue::glue
}
```

```{r results='asis'}
purrr::walk(params$months, gen_monthly_section)
```


```{r include=FALSE}
# also invisibly plot plotly outside of loop because of this issue:
# https://github.com/ropensci/plotly/issues/273

plot_ly(x = rnorm(10), type = "histogram")
```
